name: Deploy to EC2

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: start container on EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_HOSTNAME }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              # Commands to execute on the EC2 instance
              docker stop $(docker ps -q)
              cd /docker-content
              docker-compose up -d
