name: Deploy to EC2

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: start container on EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_INSTANCE_IP }}
          USER_NAME: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          cd /docker-content
          docker-compose down
          docker-compose up -d
