name: Deploy to EC2

on:
  push:
    branches:
      - main
env:
    PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    HOSTNAME: ${{ secrets.EC2_INSTANCE_IP }}
    USER_NAME: ec2-user
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH commmands on EC2 to start container
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: '${USER_NAME}@${HOSTNAME}'
          privateKey: $PRIVATE_KEY
          debug: true
          command: |
            docker-compose down
            docker-compose up -d
        
      
        
          
