name: Deploy to EC2

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop all running containers
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'docker stop $(docker ps -q)'

      - name: Change directory and run docker-compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'cd docker_content/ && docker-compose up -d'
